# Build Python environment
#FROM python:3.14-slim
FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
     curl bash nano \
     && rm -rf /var/lib/apt/lists/*

# Set up Ollama environment variables
ENV OLLAMA_HOST=http://ollama:11434
ARG OLLAMA_MODEL
EXPOSE 8501

# Set working directory for Python app
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Python application code
COPY . .

# Copy and prepare the startup script
COPY entrypoint-compose.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
